### ISSUE TITLE
Nie jest możliwe odtwarzanie konkretnego rozdziału

### ISSUE THREAD

**Issue by Piciok** [dawidpieper/tyflopodcast#1]
Kroki prowadzące do wystąpienia błędu:

1. Włączyć odtwarzanie podcastu zawierającego rozdziały np. Tyfloprzegląd.
2. Przejść na listę rozdziałów.
3. Podświetlić któryś z rozdziałów i spróbować wymusić odtworzenie od znacznika czasu rozdziału naciskając enter lub spację.

Spodziewany wynik: odtwarzanie podcastu rozpoczyna się od znacznika czasu zamieszczonego w tagu.

Wynik w chwili obecnej: odtwarzanie wznawia się od miejsca, w którym zostało wstrzymane.

Windows 10, 64 bity, NVDA jeśli może to mieć znaczenie.

**Comment by dawidpieper** [comment]
Bass (używana biblioteka dźwięku) nie umie przeskoczyć do danego momentu do chwili zbuforowania. Przy audycjach mających do, powiedzmy, 200MB i typowym łączu 2,4MB/s, zbuforowanie całości potrwa ponad minutę.
Prosiłbym o próbę potwierdzenia, czy to jest przyczyną błędu, czy też tkwi on w czymś innym.

**Comment by Piciok** [comment]
Istotnie, po odczekaniu chwili rozdziały działają jak powinny, dzięki.

**Comment by dawidpieper** [comment]
Dzięki. Postaram się w następnej wersji dodać alert na wypadek takiej sytuacji.

**Comment by Piciok** [comment]
Byłoby dobrze. Swoją drogą czy możliwa byłaby integracja innej biblioteki, która lepiej radzi sobie z zaczytywaniem strumieniowanych plików? Co na to np. FFMPEG?

**Comment by dawidpieper** [comment]
FFMPEG sam w sobie nie jest biblioteką, a programem korzystającym z bibliotek avformat, postproc i kilku innych. I zapewnia raczej wsparcie dla formatów, niż dla strumieniowania samego w sobie.
Owszem, ma taką funkcjonalność, ale należy ją traktować jako funkcjonalność programową, nie zaś biblioteczną.
Z resztą w tej sytuacji niewiele by to dało. Można albo zacząć strumieniowanie od rozdziału, ale w takim wypadku pozbawiając się możliwości przewijania wstecz, albo poczekać na zbuforowanie odpowiedniej ilości danych. I inna biblioteka nie bardzo tu pomoże. Ten sam problem dotyczy także innych programów, tylko jest w nich to mniej zauważalne, bo przewija się po kilkanaście sekund i zdąży sobie program zwykle treść dociągnąć, a nie wykonuje przeskoków o 50 procent nagrania.
W każdym razie w razie kontynuowania dyskusji prosiłbym o utworzenie osobnej issue, bo ta jest technicznie już zamknięta. :)

**Comment by webczat** [comment]
A przypadkiem libavformat nie obsługuje bezpośrednio http i możliwości seekowania? pewnie wymaga to obsługi range requests, jak to działa nie wiem, ale na pewno da się to włączyć. Piszę tutaj dla uproszczenia, jeśli to ma jakikolwiek sens to nowy ticket można pewnie zrobić.

**Comment by dawidpieper** [comment]
Pasek postępu przy buforowaniu wdrożony w wersji 0.5, commit ba09c8cb8d76eb2235dbcf13558519e976e74433
