### ISSUE TITLE
Sugestia nowej funkcji: regulacja tempa odtwarzania

### ISSUE THREAD

**Issue by Piciok** [dawidpieper/tyflopodcast#2]
Z uwagi na długość audycji, wiele osób decyduje się na odtwarzanie ich w zmienionym (najczęściej przyspieszonym) tempie. Czy możliwe byłoby dodanie możliwości zmiany tempa w taki sposób, by nie wpływała ona na wysokość z jaką odtwarzany jest plik?

**Comment by dawidpieper** [comment]
Nie jest to funkcja trudna do implementacji sama w sobie, ale cięższa technicznie. To znaczy jest to wąska granica między funkcjonalnością, a nadmiernym skomplikowaniem interfejsu.
Jeśli nie chcemy pisać własnych kontrolek lub przepisywać połowy metod istniejących, a nie jest to celem tego projektu, musimy poruszać się w ramach tego, co oferuje natywnie Windows Forms. A więc stworzyć kolejny suwak, który już rozepnie okno odtwarzania do całkiem sporej liczby kontrolek (suwaki czasu i głośności, lista rozdziałów i cztery przyciski: Play/pauza, Pobierz, Komentarze, Zamknij).
W każdym razie sprawa jest do przedyskutowania.

**Comment by Piciok** [comment]
A gdyby tak dodać skróty klawiszowe przyspieszające i zwalniające? Domyślam się, że trzeba by jakoś to potem udokumentować no i może Twoja wizja nie zakłada ukrytych funkcji bez widocznych odpowiedników w interfejsie, ale taka moja sugestia na ten moment.

**Comment by dawidpieper** [comment]
W nowej wersji zdecydowałem się jednak na nowy suwak tempa odtwarzania, propozycja zrealizowana.
0492bdc
